FROM centos

RUN yum -y -q install java-1.7.0-openjdk.x86_64
RUN wget -q -P /opt https://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar

EXPOSE 4444

CMD ["java", "-jar", "/opt/selenium-server-standalone-2.39.0.jar", "-role", "hub"]
